-- Philippine geographic reference data (PSGC) — safe for re-runs
-- =========================================================
-- REGIONS
-- =========================================================
INSERT INTO wims.ref_regions (region_name, region_code) VALUES
  ('National Capital Region',                         'NCR'),
  ('Ilocos Region',                                   'REGION_I'),
  ('Cagayan Valley',                                  'REGION_II'),
  ('Central Luzon',                                   'REGION_III'),
  ('CALABARZON',                                      'REGION_IV_A'),
  ('MIMAROPA',                                        'REGION_IV_B'),
  ('Bicol Region',                                    'REGION_V'),
  ('Western Visayas',                                 'REGION_VI'),
  ('Central Visayas',                                 'REGION_VII'),
  ('Eastern Visayas',                                 'REGION_VIII'),
  ('Zamboanga Peninsula',                             'REGION_IX'),
  ('Northern Mindanao',                               'REGION_X'),
  ('Davao Region',                                    'REGION_XI'),
  ('SOCCSKSARGEN',                                    'REGION_XII'),
  ('Caraga',                                          'REGION_XIII'),
  ('Cordillera Administrative Region',                'CAR'),
  ('Bangsamoro Autonomous Region in Muslim Mindanao', 'BARMM')
ON CONFLICT (region_code) DO NOTHING;

-- =========================================================
-- PROVINCES  (WHERE NOT EXISTS — no UNIQUE constraint)
-- =========================================================
INSERT INTO wims.ref_provinces (region_id, province_name)
SELECT r.region_id, v.pname
FROM (VALUES
  ('NCR',         'Metro Manila'),
  ('REGION_I',    'Ilocos Norte'),
  ('REGION_I',    'Ilocos Sur'),
  ('REGION_I',    'La Union'),
  ('REGION_I',    'Pangasinan'),
  ('REGION_II',   'Batanes'),
  ('REGION_II',   'Cagayan'),
  ('REGION_II',   'Isabela'),
  ('REGION_II',   'Nueva Vizcaya'),
  ('REGION_II',   'Quirino'),
  ('REGION_III',  'Aurora'),
  ('REGION_III',  'Bataan'),
  ('REGION_III',  'Bulacan'),
  ('REGION_III',  'Nueva Ecija'),
  ('REGION_III',  'Pampanga'),
  ('REGION_III',  'Tarlac'),
  ('REGION_III',  'Zambales'),
  ('REGION_IV_A', 'Batangas'),
  ('REGION_IV_A', 'Cavite'),
  ('REGION_IV_A', 'Laguna'),
  ('REGION_IV_A', 'Quezon'),
  ('REGION_IV_A', 'Rizal'),
  ('REGION_IV_B', 'Marinduque'),
  ('REGION_IV_B', 'Occidental Mindoro'),
  ('REGION_IV_B', 'Oriental Mindoro'),
  ('REGION_IV_B', 'Palawan'),
  ('REGION_IV_B', 'Romblon'),
  ('REGION_V',    'Albay'),
  ('REGION_V',    'Camarines Norte'),
  ('REGION_V',    'Camarines Sur'),
  ('REGION_V',    'Catanduanes'),
  ('REGION_V',    'Masbate'),
  ('REGION_V',    'Sorsogon'),
  ('REGION_VI',   'Aklan'),
  ('REGION_VI',   'Antique'),
  ('REGION_VI',   'Capiz'),
  ('REGION_VI',   'Guimaras'),
  ('REGION_VI',   'Iloilo'),
  ('REGION_VI',   'Negros Occidental'),
  ('REGION_VII',  'Bohol'),
  ('REGION_VII',  'Cebu'),
  ('REGION_VII',  'Negros Oriental'),
  ('REGION_VII',  'Siquijor'),
  ('REGION_VIII', 'Biliran'),
  ('REGION_VIII', 'Eastern Samar'),
  ('REGION_VIII', 'Leyte'),
  ('REGION_VIII', 'Northern Samar'),
  ('REGION_VIII', 'Samar'),
  ('REGION_VIII', 'Southern Leyte'),
  ('REGION_IX',   'Zamboanga del Norte'),
  ('REGION_IX',   'Zamboanga del Sur'),
  ('REGION_IX',   'Zamboanga Sibugay'),
  ('REGION_X',    'Bukidnon'),
  ('REGION_X',    'Camiguin'),
  ('REGION_X',    'Lanao del Norte'),
  ('REGION_X',    'Misamis Occidental'),
  ('REGION_X',    'Misamis Oriental'),
  ('REGION_XI',   'Davao de Oro'),
  ('REGION_XI',   'Davao del Norte'),
  ('REGION_XI',   'Davao del Sur'),
  ('REGION_XI',   'Davao Occidental'),
  ('REGION_XI',   'Davao Oriental'),
  ('REGION_XII',  'Cotabato'),
  ('REGION_XII',  'Sarangani'),
  ('REGION_XII',  'South Cotabato'),
  ('REGION_XII',  'Sultan Kudarat'),
  ('REGION_XIII', 'Agusan del Norte'),
  ('REGION_XIII', 'Agusan del Sur'),
  ('REGION_XIII', 'Dinagat Islands'),
  ('REGION_XIII', 'Surigao del Norte'),
  ('REGION_XIII', 'Surigao del Sur'),
  ('CAR',         'Abra'),
  ('CAR',         'Apayao'),
  ('CAR',         'Benguet'),
  ('CAR',         'Ifugao'),
  ('CAR',         'Kalinga'),
  ('CAR',         'Mountain Province'),
  ('BARMM',       'Basilan'),
  ('BARMM',       'Lanao del Sur'),
  ('BARMM',       'Maguindanao del Norte'),
  ('BARMM',       'Maguindanao del Sur'),
  ('BARMM',       'Sulu'),
  ('BARMM',       'Tawi-Tawi')
) AS v(rcode, pname)
JOIN wims.ref_regions r ON r.region_code = v.rcode
WHERE NOT EXISTS (
  SELECT 1 FROM wims.ref_provinces p
  WHERE p.region_id = r.region_id AND p.province_name = v.pname
);

-- =========================================================
-- CITIES / MUNICIPALITIES
-- =========================================================
INSERT INTO wims.ref_cities (province_id, city_name)
SELECT p.province_id, v.cname
FROM (VALUES
  ('NCR','Metro Manila','City of Manila'),
  ('NCR','Metro Manila','Quezon City'),
  ('NCR','Metro Manila','City of Caloocan'),
  ('NCR','Metro Manila','City of Las Piñas'),
  ('NCR','Metro Manila','City of Makati'),
  ('NCR','Metro Manila','City of Malabon'),
  ('NCR','Metro Manila','City of Mandaluyong'),
  ('NCR','Metro Manila','City of Marikina'),
  ('NCR','Metro Manila','City of Muntinlupa'),
  ('NCR','Metro Manila','City of Navotas'),
  ('NCR','Metro Manila','City of Parañaque'),
  ('NCR','Metro Manila','City of Pasay'),
  ('NCR','Metro Manila','City of Pasig'),
  ('NCR','Metro Manila','City of San Juan'),
  ('NCR','Metro Manila','City of Taguig'),
  ('NCR','Metro Manila','City of Valenzuela'),
  ('NCR','Metro Manila','Pateros'),
  ('REGION_I','Ilocos Norte','Laoag City'),
  ('REGION_I','Ilocos Norte','Adams'),
  ('REGION_I','Ilocos Norte','Bacarra'),
  ('REGION_I','Ilocos Norte','Badoc'),
  ('REGION_I','Ilocos Norte','Bangui'),
  ('REGION_I','Ilocos Norte','Banna'),
  ('REGION_I','Ilocos Norte','Burgos'),
  ('REGION_I','Ilocos Norte','Carasi'),
  ('REGION_I','Ilocos Norte','Currimao'),
  ('REGION_I','Ilocos Norte','Dingras'),
  ('REGION_I','Ilocos Norte','Dumalneg'),
  ('REGION_I','Ilocos Norte','Marcos'),
  ('REGION_I','Ilocos Norte','Nueva Era'),
  ('REGION_I','Ilocos Norte','Pagudpud'),
  ('REGION_I','Ilocos Norte','Paoay'),
  ('REGION_I','Ilocos Norte','Pasuquin'),
  ('REGION_I','Ilocos Norte','Piddig'),
  ('REGION_I','Ilocos Norte','Pinili'),
  ('REGION_I','Ilocos Norte','San Nicolas'),
  ('REGION_I','Ilocos Norte','Sarrat'),
  ('REGION_I','Ilocos Norte','Solsona'),
  ('REGION_I','Ilocos Norte','Vintar'),
  ('REGION_I','Ilocos Sur','Vigan City'),
  ('REGION_I','Ilocos Sur','Alilem'),
  ('REGION_I','Ilocos Sur','Banayoyo'),
  ('REGION_I','Ilocos Sur','Bantay'),
  ('REGION_I','Ilocos Sur','Burgos'),
  ('REGION_I','Ilocos Sur','Cabugao'),
  ('REGION_I','Ilocos Sur','Candon City'),
  ('REGION_I','Ilocos Sur','Caoayan'),
  ('REGION_I','Ilocos Sur','Cervantes'),
  ('REGION_I','Ilocos Sur','Galimuyod'),
  ('REGION_I','Ilocos Sur','Gregorio del Pilar'),
  ('REGION_I','Ilocos Sur','Lidlidda'),
  ('REGION_I','Ilocos Sur','Magsingal'),
  ('REGION_I','Ilocos Sur','Nagbukel'),
  ('REGION_I','Ilocos Sur','Narvacan'),
  ('REGION_I','Ilocos Sur','Quirino'),
  ('REGION_I','Ilocos Sur','Salcedo'),
  ('REGION_I','Ilocos Sur','San Emilio'),
  ('REGION_I','Ilocos Sur','San Esteban'),
  ('REGION_I','Ilocos Sur','San Ildefonso'),
  ('REGION_I','Ilocos Sur','San Juan'),
  ('REGION_I','Ilocos Sur','San Vicente'),
  ('REGION_I','Ilocos Sur','Santa'),
  ('REGION_I','Ilocos Sur','Santa Catalina'),
  ('REGION_I','Ilocos Sur','Santa Cruz'),
  ('REGION_I','Ilocos Sur','Santa Lucia'),
  ('REGION_I','Ilocos Sur','Santa Maria'),
  ('REGION_I','Ilocos Sur','Santiago'),
  ('REGION_I','Ilocos Sur','Santo Domingo'),
  ('REGION_I','Ilocos Sur','Sigay'),
  ('REGION_I','Ilocos Sur','Sinait'),
  ('REGION_I','Ilocos Sur','Sugpon'),
  ('REGION_I','Ilocos Sur','Suyo'),
  ('REGION_I','Ilocos Sur','Tagudin'),
  ('REGION_I','La Union','San Fernando City'),
  ('REGION_I','La Union','Agoo'),
  ('REGION_I','La Union','Aringay'),
  ('REGION_I','La Union','Bacnotan'),
  ('REGION_I','La Union','Bagulin'),
  ('REGION_I','La Union','Balaoan'),
  ('REGION_I','La Union','Bangar'),
  ('REGION_I','La Union','Bauang'),
  ('REGION_I','La Union','Burgos'),
  ('REGION_I','La Union','Caba'),
  ('REGION_I','La Union','Luna'),
  ('REGION_I','La Union','Naguilian'),
  ('REGION_I','La Union','Pugo'),
  ('REGION_I','La Union','Rosario'),
  ('REGION_I','La Union','San Gabriel'),
  ('REGION_I','La Union','San Juan'),
  ('REGION_I','La Union','Santo Tomas'),
  ('REGION_I','La Union','Santol'),
  ('REGION_I','La Union','Sudipen'),
  ('REGION_I','La Union','Tubao'),
  ('REGION_I','Pangasinan','Dagupan City'),
  ('REGION_I','Pangasinan','San Carlos City'),
  ('REGION_I','Pangasinan','Urdaneta City'),
  ('REGION_I','Pangasinan','Alaminos City'),
  ('REGION_I','Pangasinan','Agno'),
  ('REGION_I','Pangasinan','Aguilar'),
  ('REGION_I','Pangasinan','Alcala'),
  ('REGION_I','Pangasinan','Anda'),
  ('REGION_I','Pangasinan','Asingan'),
  ('REGION_I','Pangasinan','Balungao'),
  ('REGION_I','Pangasinan','Bani'),
  ('REGION_I','Pangasinan','Basista'),
  ('REGION_I','Pangasinan','Bautista'),
  ('REGION_I','Pangasinan','Bayambang'),
  ('REGION_I','Pangasinan','Binalonan'),
  ('REGION_I','Pangasinan','Binmaley'),
  ('REGION_I','Pangasinan','Bolinao'),
  ('REGION_I','Pangasinan','Bugallon'),
  ('REGION_I','Pangasinan','Burgos'),
  ('REGION_I','Pangasinan','Calasiao'),
  ('REGION_I','Pangasinan','Dasol'),
  ('REGION_I','Pangasinan','Infanta'),
  ('REGION_I','Pangasinan','Labrador'),
  ('REGION_I','Pangasinan','Laoac'),
  ('REGION_I','Pangasinan','Lingayen'),
  ('REGION_I','Pangasinan','Mabini'),
  ('REGION_I',
