-- 25_cities_region4.sql
-- Dependencies: 21_all_regions.sql (provinces for regions 6 and 7 must exist)
-- Idempotent: YES (ON CONFLICT DO NOTHING)
-- Populates ref_cities for Region IV-A (CALABARZON) and Region IV-B (MIMAROPA).
-- Additional regions will be added in subsequent migration files.

BEGIN;

INSERT INTO wims.ref_cities (province_id, city_name)
SELECT p.province_id, v.cname
FROM (VALUES
  -- Region IV-A: Batangas
  ('IV-A', 'Batangas', 'Agoncillo'),
  ('IV-A', 'Batangas', 'Alitagtag'),
  ('IV-A', 'Batangas', 'Balayan'),
  ('IV-A', 'Batangas', 'Balete'),
  ('IV-A', 'Batangas', 'Batangas City'),
  ('IV-A', 'Batangas', 'Bauan'),
  ('IV-A', 'Batangas', 'Calaca'),
  ('IV-A', 'Batangas', 'Calatagan'),
  ('IV-A', 'Batangas', 'Cuenca'),
  ('IV-A', 'Batangas', 'Ibaan'),
  ('IV-A', 'Batangas', 'Laurel'),
  ('IV-A', 'Batangas', 'Lemery'),
  ('IV-A', 'Batangas', 'Lian'),
  ('IV-A', 'Batangas', 'Lipa City'),
  ('IV-A', 'Batangas', 'Lobo'),
  ('IV-A', 'Batangas', 'Mabini'),
  ('IV-A', 'Batangas', 'Malvar'),
  ('IV-A', 'Batangas', 'Mataasnakahoy'),
  ('IV-A', 'Batangas', 'Nasugbu'),
  ('IV-A', 'Batangas', 'Padre Garcia'),
  ('IV-A', 'Batangas', 'Rosario'),
  ('IV-A', 'Batangas', 'San Jose'),
  ('IV-A', 'Batangas', 'San Juan'),
  ('IV-A', 'Batangas', 'San Luis'),
  ('IV-A', 'Batangas', 'San Nicolas'),
  ('IV-A', 'Batangas', 'San Pascual'),
  ('IV-A', 'Batangas', 'Santa Teresita'),
  ('IV-A', 'Batangas', 'Santo Tomas'),
  ('IV-A', 'Batangas', 'Taal'),
  ('IV-A', 'Batangas', 'Talisay'),
  ('IV-A', 'Batangas', 'Tanauan City'),
  ('IV-A', 'Batangas', 'Taysan'),
  ('IV-A', 'Batangas', 'Tingloy'),
  ('IV-A', 'Batangas', 'Tuy'),

  -- Region IV-A: Cavite
  ('IV-A', 'Cavite', 'Alfonso'),
  ('IV-A', 'Cavite', 'Amadeo'),
  ('IV-A', 'Cavite', 'Bacoor City'),
  ('IV-A', 'Cavite', 'Carmona'),
  ('IV-A', 'Cavite', 'Cavite City'),
  ('IV-A', 'Cavite', 'Dasmarinas City'),
  ('IV-A', 'Cavite', 'General Emilio Aguinaldo'),
  ('IV-A', 'Cavite', 'General Mariano Alvarez'),
  ('IV-A', 'Cavite', 'General Trias City'),
  ('IV-A', 'Cavite', 'Imus City'),
  ('IV-A', 'Cavite', 'Indang'),
  ('IV-A', 'Cavite', 'Kawit'),
  ('IV-A', 'Cavite', 'Magallanes'),
  ('IV-A', 'Cavite', 'Maragondon'),
  ('IV-A', 'Cavite', 'Mendez'),
  ('IV-A', 'Cavite', 'Naic'),
  ('IV-A', 'Cavite', 'Noveleta'),
  ('IV-A', 'Cavite', 'Rosario'),
  ('IV-A', 'Cavite', 'Silang'),
  ('IV-A', 'Cavite', 'Tagaytay City'),
  ('IV-A', 'Cavite', 'Tanza'),
  ('IV-A', 'Cavite', 'Ternate'),
  ('IV-A', 'Cavite', 'Trece Martires City'),

  -- Region IV-A: Laguna
  ('IV-A', 'Laguna', 'Alaminos'),
  ('IV-A', 'Laguna', 'Bay'),
  ('IV-A', 'Laguna', 'Binan City'),
  ('IV-A', 'Laguna', 'Cabuyao City'),
  ('IV-A', 'Laguna', 'Calamba City'),
  ('IV-A', 'Laguna', 'Calauan'),
  ('IV-A', 'Laguna', 'Cavinti'),
  ('IV-A', 'Laguna', 'Famy'),
  ('IV-A', 'Laguna', 'Kalayaan'),
  ('IV-A', 'Laguna', 'Liliw'),
  ('IV-A', 'Laguna', 'Los Banos'),
  ('IV-A', 'Laguna', 'Luisiana'),
  ('IV-A', 'Laguna', 'Lumban'),
  ('IV-A', 'Laguna', 'Mabitac'),
  ('IV-A', 'Laguna', 'Magdalena'),
  ('IV-A', 'Laguna', 'Majayjay'),
  ('IV-A', 'Laguna', 'Nagcarlan'),
  ('IV-A', 'Laguna', 'Paete'),
  ('IV-A', 'Laguna', 'Pagsanjan'),
  ('IV-A', 'Laguna', 'Pakil'),
  ('IV-A', 'Laguna', 'Pangil'),
  ('IV-A', 'Laguna', 'Pila'),
  ('IV-A', 'Laguna', 'Rizal'),
  ('IV-A', 'Laguna', 'San Pablo City'),
  ('IV-A', 'Laguna', 'San Pedro City'),
  ('IV-A', 'Laguna', 'Santa Cruz'),
  ('IV-A', 'Laguna', 'Santa Maria'),
  ('IV-A', 'Laguna', 'Santa Rosa City'),
  ('IV-A', 'Laguna', 'Siniloan'),
  ('IV-A', 'Laguna', 'Victoria'),

  -- Region IV-A: Quezon
  ('IV-A', 'Quezon', 'Agdangan'),
  ('IV-A', 'Quezon', 'Alabat'),
  ('IV-A', 'Quezon', 'Atimonan'),
  ('IV-A', 'Quezon', 'Buenavista'),
  ('IV-A', 'Quezon', 'Burdeos'),
  ('IV-A', 'Quezon', 'Calauag'),
  ('IV-A', 'Quezon', 'Candelaria'),
  ('IV-A', 'Quezon', 'Catanauan'),
  ('IV-A', 'Quezon', 'Dolores'),
  ('IV-A', 'Quezon', 'General Luna'),
  ('IV-A', 'Quezon', 'General Nakar'),
  ('IV-A', 'Quezon', 'Guinayangan'),
  ('IV-A', 'Quezon', 'Gumaca'),
  ('IV-A', 'Quezon', 'Infanta'),
  ('IV-A', 'Quezon', 'Jomalig'),
  ('IV-A', 'Quezon', 'Lopez'),
  ('IV-A', 'Quezon', 'Lucban'),
  ('IV-A', 'Quezon', 'Lucena City'),
  ('IV-A', 'Quezon', 'Macalelon'),
  ('IV-A', 'Quezon', 'Mauban'),
  ('IV-A', 'Quezon', 'Mulanay'),
  ('IV-A', 'Quezon', 'Padre Burgos'),
  ('IV-A', 'Quezon', 'Pagbilao'),
  ('IV-A', 'Quezon', 'Panukulan'),
  ('IV-A', 'Quezon', 'Patnanungan'),
  ('IV-A', 'Quezon', 'Perez'),
  ('IV-A', 'Quezon', 'Pitogo'),
  ('IV-A', 'Quezon', 'Plaridel'),
  ('IV-A', 'Quezon', 'Polillo'),
  ('IV-A', 'Quezon', 'Quezon'),
  ('IV-A', 'Quezon', 'Real'),
  ('IV-A', 'Quezon', 'Sampaloc'),
  ('IV-A', 'Quezon', 'San Andres'),
  ('IV-A', 'Quezon', 'San Antonio'),
  ('IV-A', 'Quezon', 'San Francisco'),
  ('IV-A', 'Quezon', 'San Narciso'),
  ('IV-A', 'Quezon', 'Sariaya'),
  ('IV-A', 'Quezon', 'Tagkawayan'),
  ('IV-A', 'Quezon', 'Tayabas City'),
  ('IV-A', 'Quezon', 'Tiaong'),
  ('IV-A', 'Quezon', 'Unisan'),

  -- Region IV-A: Rizal
  ('IV-A', 'Rizal', 'Angono'),
  ('IV-A', 'Rizal', 'Antipolo City'),
  ('IV-A', 'Rizal', 'Baras'),
  ('IV-A', 'Rizal', 'Binangonan'),
  ('IV-A', 'Rizal', 'Cainta'),
  ('IV-A', 'Rizal', 'Cardona'),
  ('IV-A', 'Rizal', 'Jala-Jala'),
  ('IV-A', 'Rizal', 'Morong'),
  ('IV-A', 'Rizal', 'Pililla'),
  ('IV-A', 'Rizal', 'Rodriguez'),
  ('IV-A', 'Rizal', 'San Mateo'),
  ('IV-A', 'Rizal', 'Tanay'),
  ('IV-A', 'Rizal', 'Taytay'),
  ('IV-A', 'Rizal', 'Teresa'),

  -- Region IV-B: Marinduque
  ('IV-B', 'Marinduque', 'Boac'),
  ('IV-B', 'Marinduque', 'Buenavista'),
  ('IV-B', 'Marinduque', 'Gasan'),
  ('IV-B', 'Marinduque', 'Mogpog'),
  ('IV-B', 'Marinduque', 'Santa Cruz'),
  ('IV-B', 'Marinduque', 'Torrijos'),

  -- Region IV-B: Occidental Mindoro
  ('IV-B', 'Occidental Mindoro', 'Abra de Ilog'),
  ('IV-B', 'Occidental Mindoro', 'Calintaan'),
  ('IV-B', 'Occidental Mindoro', 'Looc'),
  ('IV-B', 'Occidental Mindoro', 'Lubang'),
  ('IV-B', 'Occidental Mindoro', 'Magsaysay'),
  ('IV-B', 'Occidental Mindoro', 'Mamburao'),
  ('IV-B', 'Occidental Mindoro', 'Paluan'),
  ('IV-B', 'Occidental Mindoro', 'Rizal'),
  ('IV-B', 'Occidental Mindoro', 'Sablayan'),
  ('IV-B', 'Occidental Mindoro', 'San Jose'),
  ('IV-B', 'Occidental Mindoro', 'Santa Cruz'),

  -- Region IV-B: Oriental Mindoro
  ('IV-B', 'Oriental Mindoro', 'Baco'),
  ('IV-B', 'Oriental Mindoro', 'Bansud'),
  ('IV-B', 'Oriental Mindoro', 'Bongabong'),
  ('IV-B', 'Oriental Mindoro', 'Bulalacao'),
  ('IV-B', 'Oriental Mindoro', 'Calapan City'),
  ('IV-B', 'Oriental Mindoro', 'Gloria'),
  ('IV-B', 'Oriental Mindoro', 'Mansalay'),
  ('IV-B', 'Oriental Mindoro', 'Naujan'),
  ('IV-B', 'Oriental Mindoro', 'Pinamalayan'),
  ('IV-B', 'Oriental Mindoro', 'Pola'),
  ('IV-B', 'Oriental Mindoro', 'Puerto Galera'),
  ('IV-B', 'Oriental Mindoro', 'Roxas'),
  ('IV-B', 'Oriental Mindoro', 'San Teodoro'),
  ('IV-B', 'Oriental Mindoro', 'Socorro'),
  ('IV-B', 'Oriental Mindoro', 'Victoria'),

  -- Region IV-B: Palawan
  ('IV-B', 'Palawan', 'Aborlan'),
  ('IV-B', 'Palawan', 'Agutaya'),
  ('IV-B', 'Palawan', 'Araceli'),
  ('IV-B', 'Palawan', 'Balabac'),
  ('IV-B', 'Palawan', 'Bataraza'),
  ('IV-B', 'Palawan', 'Brooke''s Point'),
  ('IV-B', 'Palawan', 'Busuanga'),
  ('IV-B', 'Palawan', 'Cagayancillo'),
  ('IV-B', 'Palawan', 'Coron'),
  ('IV-B', 'Palawan', 'Culion'),
  ('IV-B', 'Palawan', 'Dumaran'),
  ('IV-B', 'Palawan', 'El Nido'),
  ('IV-B', 'Palawan', 'Kalayaan'),
  ('IV-B', 'Palawan', 'Linapacan'),
  ('IV-B', 'Palawan', 'Magsaysay'),
  ('IV-B', 'Palawan', 'Narra'),
  ('IV-B', 'Palawan', 'Puerto Princesa City'),
  ('IV-B', 'Palawan', 'Quezon'),
  ('IV-B', 'Palawan', 'Rizal'),
  ('IV-B', 'Palawan', 'Roxas'),
  ('IV-B', 'Palawan', 'San Vicente'),
  ('IV-B', 'Palawan', 'Sofronio Espanola'),
  ('IV-B', 'Palawan', 'Taytay'),

  -- Region IV-B: Romblon
  ('IV-B', 'Romblon', 'Alcantara'),
  ('IV-B', 'Romblon', 'Banton'),
  ('IV-B', 'Romblon', 'Cajidiocan'),
  ('IV-B', 'Romblon', 'Calatrava'),
  ('IV-B', 'Romblon', 'Concepcion'),
  ('IV-B', 'Romblon', 'Corcuera'),
  ('IV-B', 'Romblon', 'Ferrol'),
  ('IV-B', 'Romblon', 'Looc'),
  ('IV-B', 'Romblon', 'Magdiwang'),
  ('IV-B', 'Romblon', 'Odiongan'),
  ('IV-B', 'Romblon', 'Romblon'),
  ('IV-B', 'Romblon', 'San Agustin'),
  ('IV-B', 'Romblon', 'San Andres'),
  ('IV-B', 'Romblon', 'San Fernando'),
  ('IV-B', 'Romblon', 'San Jose'),
  ('IV-B', 'Romblon', 'Santa Fe'),
  ('IV-B', 'Romblon', 'Santa Maria')
) AS v(rcode, pname, cname)
JOIN wims.ref_regions r ON r.region_code = v.rcode
JOIN wims.ref_provinces p ON p.province_name = v.pname AND p.region_id = r.region_id
WHERE NOT EXISTS (
  SELECT 1 FROM wims.ref_cities c
  WHERE c.province_id = p.province_id AND c.city_name = v.cname
);

COMMIT;
