-- 26_cities_remaining_regions.sql
-- Dependencies: 21_all_regions.sql (all regions + provinces must exist)
-- Idempotent: YES (WHERE NOT EXISTS guard)
-- Populates ref_cities for all PH regions not yet covered by 25_cities_region4.sql.
-- Covers: CAR, Region I, II, III, V, VI, VII, VIII, IX, X, XI, XII, XIII, BARMM, NIR.
-- Source: Proposed-New-AFOR_Nov-2025.xlsx (List sheet, column E).

BEGIN;

INSERT INTO wims.ref_cities (province_id, city_name)
SELECT p.province_id, v.cname
FROM (VALUES

  -- ── CAR ────────────────────────────────────────────────────────────────────
  ('CAR','Abra','Bangued'),('CAR','Abra','Boliney'),('CAR','Abra','Bucay'),
  ('CAR','Abra','Bucloc'),('CAR','Abra','Daguioman'),('CAR','Abra','Danglas'),
  ('CAR','Abra','Dolores'),('CAR','Abra','La Paz'),('CAR','Abra','Lacub'),
  ('CAR','Abra','Lagangilang'),('CAR','Abra','Lagayan'),('CAR','Abra','Langiden'),
  ('CAR','Abra','Licuan Baay'),('CAR','Abra','Luba'),('CAR','Abra','Malibcong'),
  ('CAR','Abra','Manabo'),('CAR','Abra','Peñarrubia'),('CAR','Abra','Pidigan'),
  ('CAR','Abra','Pilar'),('CAR','Abra','Sallapadan'),('CAR','Abra','San Isidro'),
  ('CAR','Abra','San Juan'),('CAR','Abra','San Quintin'),('CAR','Abra','Tayum'),
  ('CAR','Abra','Tineg'),('CAR','Abra','Tubo'),('CAR','Abra','Villaviciosa'),

  ('CAR','Apayao','Calanasan'),('CAR','Apayao','Conner'),('CAR','Apayao','Flora'),
  ('CAR','Apayao','Kabugao'),('CAR','Apayao','Luna'),('CAR','Apayao','Pudtol'),
  ('CAR','Apayao','Santa Marcela'),

  ('CAR','Benguet','Atok'),('CAR','Benguet','Baguio City'),('CAR','Benguet','Bakun'),
  ('CAR','Benguet','Bokod'),('CAR','Benguet','Buguias'),('CAR','Benguet','Itogon'),
  ('CAR','Benguet','Kabayan'),('CAR','Benguet','Kapangan'),('CAR','Benguet','Kibungan'),
  ('CAR','Benguet','La Trinidad'),('CAR','Benguet','Mankayan'),('CAR','Benguet','Sablan'),
  ('CAR','Benguet','Tuba'),('CAR','Benguet','Tublay'),

  ('CAR','Ifugao','Aguinaldo'),('CAR','Ifugao','Alfonso Lista'),('CAR','Ifugao','Asipulo'),
  ('CAR','Ifugao','Banaue'),('CAR','Ifugao','Hingyon'),('CAR','Ifugao','Hungduan'),
  ('CAR','Ifugao','Kiangan'),('CAR','Ifugao','Lagawe'),('CAR','Ifugao','Lamut'),
  ('CAR','Ifugao','Mayoyao'),('CAR','Ifugao','Tinoc'),

  ('CAR','Kalinga','Balbalan'),('CAR','Kalinga','Lubuagan'),('CAR','Kalinga','Pasil'),
  ('CAR','Kalinga','Pinukpuk'),('CAR','Kalinga','Rizal'),('CAR','Kalinga','Tanudan'),
  ('CAR','Kalinga','Tinglayan'),('CAR','Kalinga','Tabuk City'),

  ('CAR','Mountain Province','Barlig'),('CAR','Mountain Province','Bauko'),
  ('CAR','Mountain Province','Besao'),('CAR','Mountain Province','Bontoc'),
  ('CAR','Mountain Province','Natonin'),('CAR','Mountain Province','Paracelis'),
  ('CAR','Mountain Province','Sabangan'),('CAR','Mountain Province','Sadanga'),
  ('CAR','Mountain Province','Sagada'),('CAR','Mountain Province','Tadian'),

  -- ── Region I ───────────────────────────────────────────────────────────────
  ('I','Ilocos Norte','Adams'),('I','Ilocos Norte','Bacarra'),('I','Ilocos Norte','Badoc'),
  ('I','Ilocos Norte','Bangui'),('I','Ilocos Norte','Banna'),('I','Ilocos Norte','Batac City'),
  ('I','Ilocos Norte','Burgos'),('I','Ilocos Norte','Carasi'),('I','Ilocos Norte','Currimao'),
  ('I','Ilocos Norte','Dumalneg'),('I','Ilocos Norte','Dingras'),('I','Ilocos Norte','Laoag City'),
  ('I','Ilocos Norte','Marcos'),('I','Ilocos Norte','Nueva Era'),('I','Ilocos Norte','Pagudpud'),
  ('I','Ilocos Norte','Paoay'),('I','Ilocos Norte','Pasuquin'),('I','Ilocos Norte','Piddig'),
  ('I','Ilocos Norte','Pinili'),('I','Ilocos Norte','San Nicolas'),('I','Ilocos Norte','Sarrat'),
  ('I','Ilocos Norte','Solsona'),('I','Ilocos Norte','Vintar'),

  ('I','Ilocos Sur','Alilem'),('I','Ilocos Sur','Banayoyo'),('I','Ilocos Sur','Bantay'),
  ('I','Ilocos Sur','Burgos'),('I','Ilocos Sur','Cabugao'),('I','Ilocos Sur','Candon City'),
  ('I','Ilocos Sur','Caoayan'),('I','Ilocos Sur','Cervantes'),('I','Ilocos Sur','Galimuyod'),
  ('I','Ilocos Sur','Gregorio del Pilar'),('I','Ilocos Sur','Lidlidda'),
  ('I','Ilocos Sur','Magsingal'),('I','Ilocos Sur','Nagbukel'),('I','Ilocos Sur','Narvacan'),
  ('I','Ilocos Sur','Quirino'),('I','Ilocos Sur','Salcedo'),('I','Ilocos Sur','San Emilio'),
  ('I','Ilocos Sur','San Esteban'),('I','Ilocos Sur','San Ildefonso'),
  ('I','Ilocos Sur','San Juan'),('I','Ilocos Sur','San Vicente'),('I','Ilocos Sur','Santa'),
  ('I','Ilocos Sur','Santa Catalina'),('I','Ilocos Sur','Santa Cruz'),
  ('I','Ilocos Sur','Santa Lucia'),('I','Ilocos Sur','Santa Maria'),
  ('I','Ilocos Sur','Santiago'),('I','Ilocos Sur','Santo Domingo'),('I','Ilocos Sur','Sigay'),
  ('I','Ilocos Sur','Sinait'),('I','Ilocos Sur','Sugpon'),('I','Ilocos Sur','Suyo'),
  ('I','Ilocos Sur','Tagudin'),('I','Ilocos Sur','Vigan City'),

  ('I','La Union','Agoo'),('I','La Union','Aringay'),('I','La Union','Bacnotan'),
  ('I','La Union','Bagulin'),('I','La Union','Balaoan'),('I','La Union','Bangar'),
  ('I','La Union','Bauang'),('I','La Union','Burgos'),('I','La Union','Caba'),
  ('I','La Union','Luna'),('I','La Union','Naguilian'),('I','La Union','Pugo'),
  ('I','La Union','Rosario'),('I','La Union','San Fernando City'),('I','La Union','San Gabriel'),
  ('I','La Union','San Juan'),('I','La Union','Santo Tomas'),('I','La Union','Santol'),
  ('I','La Union','Sudipen'),('I','La Union','Tubao'),

  ('I','Pangasinan','Agno'),('I','Pangasinan','Aguilar'),('I','Pangasinan','Alaminos City'),
  ('I','Pangasinan','Alcala'),('I','Pangasinan','Anda'),('I','Pangasinan','Asingan'),
  ('I','Pangasinan','Balungao'),('I','Pangasinan','Bani'),('I','Pangasinan','Basista'),
  ('I','Pangasinan','Bautista'),('I','Pangasinan','Bayambang'),('I','Pangasinan','Binalonan'),
  ('I','Pangasinan','Binmaley'),('I','Pangasinan','Bolinao'),('I','Pangasinan','Bugallon'),
  ('I','Pangasinan','Burgos'),('I','Pangasinan','Calasiao'),('I','Pangasinan','Dagupan City'),
  ('I','Pangasinan','Dasol'),('I','Pangasinan','Infanta'),('I','Pangasinan','Labrador'),
  ('I','Pangasinan','Laoac'),('I','Pangasinan','Lingayen'),('I','Pangasinan','Mabini'),
  ('I','Pangasinan','Malasiqui'),('I','Pangasinan','Manaoag'),('I','Pangasinan','Mangaldan'),
  ('I','Pangasinan','Mangatarem'),('I','Pangasinan','Mapandan'),('I','Pangasinan','Natividad'),
  ('I','Pangasinan','Pozzorubio'),('I','Pangasinan','Rosales'),
  ('I','Pangasinan','San Carlos City'),('I','Pangasinan','San Fabian'),
  ('I','Pangasinan','San Jacinto'),('I','Pangasinan','San Manuel'),
  ('I','Pangasinan','San Nicolas'),('I','Pangasinan','San Quintin'),
  ('I','Pangasinan','Santa Barbara'),('I','Pangasinan','Santa Maria'),
  ('I','Pangasinan','Santo Tomas'),('I','Pangasinan','Sison'),('I','Pangasinan','Sual'),
  ('I','Pangasinan','Tayug'),('I','Pangasinan','Umingan'),('I','Pangasinan','Urbiztondo'),
  ('I','Pangasinan','Urdaneta City'),('I','Pangasinan','Villasis'),

  -- ── Region II ──────────────────────────────────────────────────────────────
  ('II','Batanes','Basco'),('II','Batanes','Itbayat'),('II','Batanes','Ivana'),
  ('II','Batanes','Mahatao'),('II','Batanes','Sabtang'),('II','Batanes','Uyugan'),

  ('II','Cagayan','Abulug'),('II','Cagayan','Alcala'),('II','Cagayan','Allacapan'),
  ('II','Cagayan','Amulung'),('II','Cagayan','Aparri'),('II','Cagayan','Baggao'),
  ('II','Cagayan','Ballesteros'),('II','Cagayan','Buguey'),('II','Cagayan','Calayan'),
  ('II','Cagayan','Camalaniugan'),('II','Cagayan','Claveria'),('II','Cagayan','Enrile'),
  ('II','Cagayan','Gattaran'),('II','Cagayan','Gonzaga'),('II','Cagayan','Iguig'),
  ('II','Cagayan','Lal-lo'),('II','Cagayan','Lasam'),('II','Cagayan','Pamplona'),
  ('II','Cagayan','Peñablanca'),('II','Cagayan','Piat'),('II','Cagayan','Rizal'),
  ('II','Cagayan','Sanchez Mira'),('II','Cagayan','Solana'),
  ('II','Cagayan','Santa Praxedes'),('II','Cagayan','Santa Ana'),
  ('II','Cagayan','Santa Teresita'),('II','Cagayan','Santo Niño'),('II','Cagayan','Tuao'),
  ('II','Cagayan','Tuguegarao City'),

  ('II','Isabela','Alicia'),('II','Isabela','Angadanan'),('II','Isabela','Aurora'),
  ('II','Isabela','Benito Soliven'),('II','Isabela','Divilican'),('II','Isabela','Maconacon'),
  ('II','Isabela','Palanan'),('II','Isabela','Dinapigue'),('II','Isabela','Burgos'),
  ('II','Isabela','Cabagan'),('II','Isabela','Cabatuan'),('II','Isabela','Cauayan City'),
  ('II','Isabela','Cordon'),('II','Isabela','Delfin Albano'),('II','Isabela','Echague'),
  ('II','Isabela','Gamu'),('II','Isabela','Ilagan City'),('II','Isabela','Jones'),
  ('II','Isabela','Luna'),('II','Isabela','Mallig'),('II','Isabela','Naguilian'),
  ('II','Isabela','Quezon'),('II','Isabela','Quirino'),('II','Isabela','Ramon'),
  ('II','Isabela','Reina Mercedes'),('II','Isabela','Roxas'),('II','Isabela','San Agustin'),
  ('II','Isabela','San Guillermo'),('II','Isabela','San Isidro'),('II','Isabela','San Manuel'),
  ('II','Isabela','San Mariano'),('II','Isabela','San Mateo'),('II','Isabela','San Pablo'),
  ('II','Isabela','Santa Maria'),('II','Isabela','Santiago City'),('II','Isabela','Santo Tomas'),
  ('II','Isabela','Tumauini'),

  ('II','Nueva Vizcaya','Alfonso Castañeda'),('II','Nueva Vizcaya','Ambaguio'),
  ('II','Nueva Vizcaya','Aritao'),('II','Nueva Vizcaya','Bagabag'),
  ('II','Nueva Vizcaya','Bambang'),('II','Nueva Vizcaya','Bayombong'),
  ('II','Nueva Vizcaya','Diadi'),('II','Nueva Vizcaya','Dupax del Norte'),
  ('II','Nueva Vizcaya','Dupax del Sur'),('II','Nueva Vizcaya','Kasibu'),
  ('II','Nueva Vizcaya','Kayapa'),('II','Nueva Vizcaya','Quezon'),
  ('II','Nueva Vizcaya','Santa Fe'),('II','Nueva Vizcaya','Solano'),
  ('II','Nueva Vizcaya','Villaverde'),

  ('II','Quirino','Aglipay'),('II','Quirino','Cabarroguis'),('II','Quirino','Diffun'),
  ('II','Quirino','Maddela'),('II','Quirino','Nagtipunan'),('II','Quirino','Saguday'),

  -- ── Region III ─────────────────────────────────────────────────────────────
  ('III','Aurora','Baler'),('III','Aurora','Casiguran'),('III','Aurora','Dilasag'),
  ('III','Aurora','Dinalungan'),('III','Aurora','Dingalan'),('III','Aurora','Dipaculao'),
  ('III','Aurora','Maria Aurora'),('III','Aurora','San Luis'),

  ('III','Bataan','Abucay'),('III','Bataan','Bagac'),('III','Bataan','Balanga City'),
  ('III','Bataan','Dinalupihan'),('III','Bataan','Hermosa'),('III','Bataan','Limay'),
  ('III','Bataan','Mariveles'),('III','Bataan','Morong'),('III','Bataan','Orani'),
  ('III','Bataan','Orion'),('III','Bataan','Pilar'),('III','Bataan','Samal'),

  ('III','Bulacan','Angat'),('III','Bulacan','Balagtas'),('III','Bulacan','Baliuag'),
  ('III','Bulacan','Bocaue'),('III','Bulacan','Bulacan'),('III','Bulacan','Bustos'),
  ('III','Bulacan','Calumpit'),('III','Bulacan','Doña Remedios Trinidad'),
  ('III','Bulacan','Guiguinto'),('III','Bulacan','Hagonoy'),('III','Bulacan','Malolos City'),
  ('III','Bulacan','Marilao'),('III','Bulacan','Meycauayan City'),('III','Bulacan','Norzagaray'),
  ('III','Bulacan','Obando'),('III','Bulacan','Pandi'),('III','Bulacan','Paombong'),
  ('III','Bulacan','Plaridel'),('III','Bulacan','Pulilan'),('III','Bulacan','San Ildefonso'),
  ('III','Bulacan','San Jose del Monte City'),('III','Bulacan','San Miguel'),
  ('III','Bulacan','San Rafael'),('III','Bulacan','Santa Maria'),

  ('III','Nueva Ecija','Aliaga'),('III','Nueva Ecija','Bongabon'),
  ('III','Nueva Ecija','Cabanatuan City'),('III','Nueva Ecija','Cabiao'),
  ('III','Nueva Ecija','Carranglan'),('III','Nueva Ecija','Cuyapo'),
  ('III','Nueva Ecija','Gabaldon'),('III','Nueva Ecija','Gapan City'),
  ('III','Nueva Ecija','General Mamerto Natividad'),('III','Nueva Ecija','General Tinio'),
  ('III','Nueva Ecija','Guimba'),('III','Nueva Ecija','Jaen'),('III','Nueva Ecija','Laur'),
  ('III','Nueva Ecija','Licab'),('III','Nueva Ecija','Llanera'),('III','Nueva Ecija','Lupao'),
  ('III','Nueva Ecija','Munoz Science City'),('III','Nueva Ecija','Nampicuan'),
  ('III','Nueva Ecija','Palayan City'),('III','Nueva Ecija','Pantabangan'),
  ('III','Nueva Ecija','Peñaranda'),('III','Nueva Ecija','Quezon'),
  ('III','Nueva Ecija','Rizal'),('III','Nueva Ecija','San Antonio'),
  ('III','Nueva Ecija','San Isidro'),('III','Nueva Ecija','San Jose City'),
  ('III','Nueva Ecija','San Leonardo'),('III','Nueva Ecija','Santa Rosa'),
  ('III','Nueva Ecija','Santo Domingo'),('III','Nueva Ecija','Talavera'),
  ('III','Nueva Ecija','Talugtug'),('III','Nueva Ecija','Zaragoza'),

  ('III','Pampanga','Angeles City'),('III','Pampanga','Apalit'),('III','Pampanga','Arayat'),
  ('III','Pampanga','Bacolor'),('III','Pampanga','Candaba'),
  ('III','Pampanga','San Fernando City'),('III','Pampanga','Floridablanca'),
  ('III','Pampanga','Guagua'),('III','Pampanga','Lubao'),('III','Pampanga','Mabalacat City'),
  ('III','Pampanga','Macabebe'),('III','Pampanga','Magalang'),('III','Pampanga','Masantol'),
  ('III','Pampanga','Mexico'),('III','Pampanga','Minalin'),('III','Pampanga','Porac'),
  ('III','Pampanga','San Luis'),('III','Pampanga','San Simon'),('III','Pampanga','Sasmuan'),
  ('III','Pampanga','Santa Rita'),('III','Pampanga','Santa Ana'),('III','Pampanga','Santo Tomas'),

  ('III','Tarlac','Anao'),('III','Tarlac','Bamban'),('III','Tarlac','Camiling'),
  ('III','Tarlac','Capas'),('III','Tarlac','Concepcion'),('III','Tarlac','Gerona'),
  ('III','Tarlac','La Paz'),('III','Tarlac','Mayantoc'),('III','Tarlac','Moncada'),
  ('III','Tarlac','Paniqui'),('III','Tarlac','Pura'),('III','Tarlac','Ramos'),
  ('III','Tarlac','San Clemente'),('III','Tarlac','San Jose'),('III','Tarlac','San Manuel'),
  ('III','Tarlac','Santa Ignacia'),('III','Tarlac','Tarlac City'),('III','Tarlac','Victoria'),

  ('III','Zambales','Botolan'),('III','Zambales','Cabangan'),('III','Zambales','Candelaria'),
  ('III','Zambales','Castillejos'),('III','Zambales','Iba'),('III','Zambales','Masinloc'),
  ('III','Zambales','Olongapo City'),('III','Zambales','Palauig'),
  ('III','Zambales','San Antonio'),('III','Zambales','San Felipe'),
  ('III','Zambales','San Marcelino'),('III','Zambales','San Narciso'),
  ('III','Zambales','Santa Cruz'),('III','Zambales','Subic'),

  -- ── Region V ───────────────────────────────────────────────────────────────
  ('V','Albay','Bacacay'),('V','Albay','Camalig'),('V','Albay','Daraga'),
  ('V','Albay','Guinobatan'),('V','Albay','Jovellar'),('V','Albay','Legazpi City'),
  ('V','Albay','Libon'),('V','Albay','Ligao City'),('V','Albay','Malilipot'),
  ('V','Albay','Malinao'),('V','Albay','Manito'),('V','Albay','Oas'),
  ('V','Albay','Pio Duran'),('V','Albay','Polangui'),('V','Albay','Rapu-Rapu'),
  ('V','Albay','Santo Domingo'),('V','Albay','Tabaco City'),('V','Albay','Tiwi'),

  ('V','Camarines Norte','Basud'),('V','Camarines Norte','Capalonga'),
  ('V','Camarines Norte','Daet'),('V','Camarines Norte','Jose Panganiban'),
  ('V','Camarines Norte','Labo'),('V','Camarines Norte','Mercedes'),
  ('V','Camarines Norte','Paracale'),('V','Camarines Norte','San Lorenzo Ruiz'),
  ('V','Camarines Norte','San Vicente'),('V','Camarines Norte','Santa Elena'),
  ('V','Camarines Norte','Talisay'),('V','Camarines Norte','Vinzons'),

  ('V','Camarines Sur','Baao'),('V','Camarines Sur','Balatan'),('V','Camarines Sur','Bato'),
  ('V','Camarines Sur','Bombon'),('V','Camarines Sur','Buhi'),('V','Camarines Sur','Bula'),
  ('V','Camarines Sur','Cabusao'),('V','Camarines Sur','Calabanga'),
  ('V','Camarines Sur','Camaligan'),('V','Camarines Sur','Canaman'),
  ('V','Camarines Sur','Caramoan'),('V','Camarines Sur','Del Gallego'),
  ('V','Camarines Sur','Gachitorena'),('V','Camarines Sur','Gainza'),
  ('V','Camarines Sur','Goa'),('V','Camarines Sur','Iriga City'),
  ('V','Camarines Sur','Lagonoy'),('V','Camarines Sur','Libmanan'),
  ('V','Camarines Sur','Lupi'),('V','Camarines Sur','Magarao'),
  ('V','Camarines Sur','Milaor'),('V','Camarines Sur','Minalabac'),
  ('V','Camarines Sur','Nabua'),('V','Camarines Sur','Naga City'),
  ('V','Camarines Sur','Ocampo'),('V','Camarines Sur','Pamplona'),
  ('V','Camarines Sur','Pasacao'),('V','Camarines Sur','Pili'),
  ('V','Camarines Sur','Presentacion'),('V','Camarines Sur','Ragay'),
  ('V','Camarines Sur','Sagnay'),('V','Camarines Sur','San Fernando'),
  ('V','Camarines Sur','San Jose'),('V','Camarines Sur','Sipocot'),
  ('V','Camarines Sur','Siruma'),('V','Camarines Sur','Tigaon'),
  ('V','Camarines Sur','Tinambac'),

  ('V','Catanduanes','Bagamanok'),('V','Catanduanes','Baras'),('V','Catanduanes','Bato'),
  ('V','Catanduanes','Caramoran'),('V','Catanduanes','Gigmoto'),('V','Catanduanes','Pandan'),
  ('V','Catanduanes','Panganiban'),('V','Catanduanes','San Andres'),
  ('V','Catanduanes','San Miguel'),('V','Catanduanes','Viga'),('V','Catanduanes','Virac'),

  ('V','Masbate','Aroroy'),('V','Masbate','Baleno'),('V','Masbate','Balud'),
  ('V','Masbate','Batuan'),('V','Masbate','Cataingan'),('V','Masbate','Cawayan'),
  ('V','Masbate','Claveria'),('V','Masbate','Dimasalang'),('V','Masbate','Esperanza'),
  ('V','Masbate','Mandaon'),('V','Masbate','Masbate City'),('V','Masbate','Milagros'),
  ('V','Masbate','Mobo'),('V','Masbate','Monreal'),('V','Masbate','Palanas'),
  ('V','Masbate','Pio V Corpuz'),('V','Masbate','Placer'),('V','Masbate','San Fernando'),
  ('V','Masbate','San Jacinto'),('V','Masbate','San Pascual'),('V','Masbate','Uson'),

  ('V','Sorsogon','Barcelona'),('V','Sorsogon','Bulan'),('V','Sorsogon','Bulusan'),
  ('V','Sorsogon','Casiguran'),('V','Sorsogon','Castilla'),('V','Sorsogon','Donsol'),
  ('V','Sorsogon','Gubat'),('V','Sorsogon','Irosin'),('V','Sorsogon','Juban'),
  ('V','Sorsogon','Magallanes'),('V','Sorsogon','Matnog'),('V','Sorsogon','Pilar'),
  ('V','Sorsogon','Prieto Diaz'),('V','Sorsogon','Santa Magdalena'),
  ('V','Sorsogon','Sorsogon City'),

  -- ── Region VI ──────────────────────────────────────────────────────────────
  ('VI','Aklan','Altavas'),('VI','Aklan','Balete'),('VI','Aklan','Banga'),
  ('VI','Aklan','Batan'),('VI','Aklan','Buruanga'),('VI','Aklan','Ibajay'),
  ('VI','Aklan','Kalibo'),('VI','Aklan','Lezo'),('VI','Aklan','Libacao'),
  ('VI','Aklan','Madalag'),('VI','Aklan','Makato'),('VI','Aklan','Malay'),
  ('VI','Aklan','Malinao'),('VI','Aklan','Nabas'),('VI','Aklan','New Washington'),
  ('VI','Aklan','Numancia'),('VI','Aklan','Tangalan'),

  ('VI','Antique','Anini-y'),('VI','Antique','Barbaza'),('VI','Antique','Belison'),
  ('VI','Antique','Bugasong'),('VI','Antique','Caluya'),('VI','Antique','Culasi'),
  ('VI','Antique','Hamtic'),('VI','Antique','Laua-an'),('VI','Antique','Libertad'),
  ('VI','Antique','Pandan'),('VI','Antique','Patnongon'),('VI','Antique','San Jose'),
  ('VI','Antique','San Remigio'),('VI','Antique','Sebaste'),('VI','Antique','Sibalom'),
  ('VI','Antique','Tibiao'),('VI','Antique','Tobias Fornier'),('VI','Antique','Valderrama'),

  ('VI','Capiz','Cuartero'),('VI','Capiz','Dao'),('VI','Capiz','Dumalag'),
  ('VI','Capiz','Dumarao'),('VI','Capiz','Ivisan'),('VI','Capiz','Jamindan'),
  ('VI','Capiz','Maayon'),('VI','Capiz','Mambusao'),('VI','Capiz','Panay'),
  ('VI','Capiz','Panitan'),('VI','Capiz','Pilar'),('VI','Capiz','Pontevedra'),
  ('VI','Capiz','President Roxas'),('VI','Capiz','Roxas City'),('VI','Capiz','Sapian'),
  ('VI','Capiz','Sigma'),('VI','Capiz','Tapaz'),

  ('VI','Guimaras','Buenavista'),('VI','Guimaras','Jordan'),
  ('VI','Guimaras','Nueva Valencia'),('VI','Guimaras','San Lorenzo'),
  ('VI','Guimaras','Sibunag'),

  ('VI','Iloilo','Ajuy'),('VI','Iloilo','Alimodian'),('VI','Iloilo','Anilao'),
  ('VI','Iloilo','Badiangan'),('VI','Iloilo','Balasan'),('VI','Iloilo','Banate'),
  ('VI','Iloilo','Barotac Nuevo'),('VI','Iloilo','Barotac Viejo'),('VI','Iloilo','Batad'),
  ('VI','Iloilo','Bingawan'),('VI','Iloilo','Cabatuan'),('VI','Iloilo','Calinog'),
  ('VI','Iloilo','Carles'),('VI','Iloilo','Concepcion'),('VI','Iloilo','Dingle'),
  ('VI','Iloilo','Dueñas'),('VI','Iloilo','Dumangas'),('VI','Iloilo','Estancia'),
  ('VI','Iloilo','Guimbal'),('VI','Iloilo','Igbaras'),('VI','Iloilo','Iloilo City'),
  ('VI','Iloilo','Janiuay'),('VI','Iloilo','Lambunao'),('VI','Iloilo','Leganes'),
  ('VI','Iloilo','Lemery'),('VI','Iloilo','Leon'),('VI','Iloilo','Maasin'),
  ('VI','Iloilo','Miagao'),('VI','Iloilo','Mina'),('VI','Iloilo','New Lucena'),
  ('VI','Iloilo','Oton'),('VI','Iloilo','Passi City'),('VI','Iloilo','Pavia'),
  ('VI','Iloilo','Pototan'),('VI','Iloilo','San Dionisio'),('VI','Iloilo','San Enrique'),
  ('VI','Iloilo','San Joaquin'),('VI','Iloilo','San Miguel'),('VI','Iloilo','San Rafael'),
  ('VI','Iloilo','Sara'),('VI','Iloilo','Santa Barbara'),('VI','Iloilo','Tigbauan'),
  ('VI','Iloilo','Tubungan'),('VI','Iloilo','Zarraga'),

  ('VI','Negros Occidental','Bacolod City'),('VI','Negros Occidental','Bago City'),
  ('VI','Negros Occidental','Binalbagan'),('VI','Negros Occidental','Cadiz City'),
  ('VI','Negros Occidental','Calatrava'),('VI','Negros Occidental','Candoni'),
  ('VI','Negros Occidental','Cauayan'),('VI','Negros Occidental','Enrique B Magalona'),
  ('VI','Negros Occidental','Escalante City'),('VI','Negros Occidental','Himamaylan City'),
  ('VI','Negros Occidental','Hinigaran'),('VI','Negros Occidental','Hinoba-an'),
  ('VI','Negros Occidental','Ilog'),('VI','Negros Occidental','Kabankalan City'),
  ('VI','Negros Occidental','La Carlota City'),('VI','Negros Occidental','La Castellana'),
  ('VI','Negros Occidental','Manapla'),('VI','Negros Occidental','Moises Padilla'),
  ('VI','Negros Occidental','Murcia'),('VI','Negros Occidental','Pulupandan'),
  ('VI','Negros Occidental','Pontevedra'),('VI','Negros Occidental','Salvador Benedicto'),
  ('VI','Negros Occidental','Sagay City'),('VI','Negros Occidental','San Carlos City'),
  ('VI','Negros Occidental','San Enrique'),('VI','Negros Occidental','Silay City'),
  ('VI','Negros Occidental','Sipalay City'),('VI','Negros Occidental','Talisay City'),
  ('VI','Negros Occidental','Toboso'),('VI','Negros Occidental','Valladolid'),
  ('VI','Negros Occidental','Victorias City'),

  -- ── Region VII ─────────────────────────────────────────────────────────────
  ('VII','Bohol','Alburquerque'),('VII','Bohol','Alicia'),('VII','Bohol','Anda'),
  ('VII','Bohol','Antequera'),('VII','Bohol','Baclayon'),('VII','Bohol','Balilihan'),
  ('VII','Bohol','Batuan'),('VII','Bohol','Bien Unido'),('VII','Bohol','Bilar'),
  ('VII','Bohol','Buenavista'),('VII','Bohol','Calape'),('VII','Bohol','Candijay'),
  ('VII','Bohol','Pres Carlos P Garcia'),('VII','Bohol','Carmen'),
  ('VII','Bohol','Catigbian'),('VII','Bohol','Clarin'),('VII','Bohol','Corella'),
  ('VII','Bohol','Cortes'),('VII','Bohol','Dagohoy'),('VII','Bohol','Danao'),
  ('VII','Bohol','Dauis'),('VII','Bohol','Dimiao'),('VII','Bohol','Duero'),
  ('VII','Bohol','Garcia Hernandez'),('VII','Bohol','Guindulman'),
  ('VII','Bohol','Inabanga'),('VII','Bohol','Jagna'),('VII','Bohol','Jetafe'),
  ('VII','Bohol','Lila'),('VII','Bohol','Loay'),('VII','Bohol','Loboc'),
  ('VII','Bohol','Loon'),('VII','Bohol','Mabini'),('VII','Bohol','Maribojoc'),
  ('VII','Bohol','Panglao'),('VII','Bohol','Pilar'),('VII','Bohol','Sagbayan'),
  ('VII','Bohol','San Isidro'),('VII','Bohol','San Miguel'),('VII','Bohol','Sevilla'),
  ('VII','Bohol','Sierra Bullones'),('VII','Bohol','Sikatuna'),
  ('VII','Bohol','Tagbilaran City'),('VII','Bohol','Talibon'),('VII','Bohol','Trinidad'),
  ('VII','Bohol','Tubigon'),('VII','Bohol','Ubay'),('VII','Bohol','Valencia'),

  ('VII','Cebu','Alcantara'),('VII','Cebu','Alcoy'),('VII','Cebu','Alegria'),
  ('VII','Cebu','Aloguinsan'),('VII','Cebu','Argao'),('VII','Cebu','Asturias'),
  ('VII','Cebu','Badian'),('VII','Cebu','Balamban'),('VII','Cebu','Bantayan'),
  ('VII','Cebu','Barili'),('VII','Cebu','Bogo City'),('VII','Cebu','Boljoon'),
  ('VII','Cebu','Borbon'),('VII','Cebu','Carcar City'),('VII','Cebu','Carmen'),
  ('VII','Cebu','Catmon'),('VII','Cebu','Cebu City'),('VII','Cebu','Compostela'),
  ('VII','Cebu','Consolacion'),('VII','Cebu','Cordova'),('VII','Cebu','Daanbantayan'),
  ('VII','Cebu','Dalaguete'),('VII','Cebu','Danao City'),('VII','Cebu','Dumanjug'),
  ('VII','Cebu','Ginatilan'),('VII','Cebu','Lapu-Lapu City'),('VII','Cebu','Liloan'),
  ('VII','Cebu','Madredejos'),('VII','Cebu','Malabuyoc'),('VII','Cebu','Mandaue City'),
  ('VII','Cebu','Medellin'),('VII','Cebu','Minglanilla'),('VII','Cebu','Moalboal'),
  ('VII','Cebu','Naga City'),('VII','Cebu','Oslob'),('VII','Cebu','Pilar'),
  ('VII','Cebu','Pinamungajan'),('VII','Cebu','Poro'),('VII','Cebu','Ronda'),
  ('VII','Cebu','Samboan'),('VII','Cebu','San Fernando'),('VII','Cebu','San Francisco'),
  ('VII','Cebu','San Remigio'),('VII','Cebu','Santander'),('VII','Cebu','Sibonga'),
  ('VII','Cebu','Sogod'),('VII','Cebu','Santa Fe'),('VII','Cebu','Tabogon'),
  ('VII','Cebu','Tabuelan'),('VII','Cebu','Talisay City'),('VII','Cebu','Toledo City'),
  ('VII','Cebu','Tuburan'),('VII','Cebu','Tudela'),

  ('VII','Negros Oriental','Amlan'),('VII','Negros Oriental','Ayungon'),
  ('VII','Negros Oriental','Bacong'),('VII','Negros Oriental','Bais City'),
  ('VII','Negros Oriental','Basay'),('VII','Negros Oriental','Bayawan City'),
  ('VII','Negros Oriental','Bindoy'),('VII','Negros Oriental','Canlaon City'),
  ('VII','Negros Oriental','Dauin'),('VII','Negros Oriental','Dumaguete City'),
  ('VII','Negros Oriental','Guihulngan City'),('VII','Negros Oriental','Jimalalud'),
  ('VII','Negros Oriental','La Libertad'),('VII','Negros Oriental','Mabinay'),
  ('VII','Negros Oriental','Manjuyod'),('VII','Negros Oriental','Pamplona'),
  ('VII','Negros Oriental','San Jose'),('VII','Negros Oriental','Siaton'),
  ('VII','Negros Oriental','Sibulan'),('VII','Negros Oriental','Santa Catalina'),
  ('VII','Negros Oriental','Tanjay City'),('VII','Negros Oriental','Tayasan'),
  ('VII','Negros Oriental','Valencia'),('VII','Negros Oriental','Vallehermoso'),
  ('VII','Negros Oriental','Zamboanguita'),

  ('VII','Siquijor','Enrique Villanueva'),('VII','Siquijor','Larena'),
  ('VII','Siquijor','Lazi'),('VII','Siquijor','Maria'),('VII','Siquijor','San Juan'),

  -- ── Region VIII ────────────────────────────────────────────────────────────
  ('VIII','Biliran','Almeria'),('VIII','Biliran','Cabucgayan'),('VIII','Biliran','Caibiran'),
  ('VIII','Biliran','Culaba'),('VIII','Biliran','Kawayan'),('VIII','Biliran','Maripipi'),
  ('VIII','Biliran','Naval'),

  ('VIII','Eastern Samar','Arteche'),('VIII','Eastern Samar','Balangiga'),
  ('VIII','Eastern Samar','Balangkayan'),('VIII','Eastern Samar','Borongan City'),
  ('VIII','Eastern Samar','Can-avid'),('VIII','Eastern Samar','Dolores'),
  ('VIII','Eastern Samar','General MacArthur'),('VIII','Eastern Samar','Giporlos'),
  ('VIII','Eastern Samar','Guiuan'),('VIII','Eastern Samar','Hernani'),
  ('VIII','Eastern Samar','Jipapad'),('VIII','Eastern Samar','Lawaan'),
  ('VIII','Eastern Samar','Llorente'),('VIII','Eastern Samar','Maslog'),
  ('VIII','Eastern Samar','Maydolong'),('VIII','Eastern Samar','Mercedes'),
  ('VIII','Eastern Samar','Oras'),('VIII','Eastern Samar','Quinapondan'),
  ('VIII','Eastern Samar','Salcedo'),('VIII','Eastern Samar','San Julian'),
  ('VIII','Eastern Samar','San Policarpo'),('VIII','Eastern Samar','Sulat'),
  ('VIII','Eastern Samar','Taft'),

  ('VIII','Leyte','Abuyog'),('VIII','Leyte','Alang-alang'),('VIII','Leyte','Albuera'),
  ('VIII','Leyte','Babatngon'),('VIII','Leyte','Barugo'),('VIII','Leyte','Bato'),
  ('VIII','Leyte','Baybay City'),('VIII','Leyte','Burauen'),('VIII','Leyte','Calubian'),
  ('VIII','Leyte','Capoocan'),('VIII','Leyte','Carigara'),('VIII','Leyte','Dagami'),
  ('VIII','Leyte','Dulag'),('VIII','Leyte','Hilongos'),('VIII','Leyte','Hindang'),
  ('VIII','Leyte','Inopacan'),('VIII','Leyte','Isabel'),('VIII','Leyte','Jaro'),
  ('VIII','Leyte','Javier'),('VIII','Leyte','Julita'),('VIII','Leyte','Kananga'),
  ('VIII','Leyte','La Paz'),('VIII','Leyte','Leyte'),('VIII','Leyte','MacArthur'),
  ('VIII','Leyte','Mahaplag'),('VIII','Leyte','Matag-ob'),('VIII','Leyte','Matalom'),
  ('VIII','Leyte','Mayorga'),('VIII','Leyte','Merida'),('VIII','Leyte','Ormoc City'),
  ('VIII','Leyte','Palo'),('VIII','Leyte','Palompon'),('VIII','Leyte','Pastrana'),
  ('VIII','Leyte','San Isidro'),('VIII','Leyte','San Miguel'),('VIII','Leyte','Santa Fe'),
  ('VIII','Leyte','Tabango'),('VIII','Leyte','Tabontabon'),('VIII','Leyte','Tacloban City'),
  ('VIII','Leyte','Tanauan'),('VIII','Leyte','Tolosa'),('VIII','Leyte','Tunga'),
  ('VIII','Leyte','Villaba'),

  ('VIII','Northern Samar','Allen'),('VIII','Northern Samar','Biri'),
  ('VIII','Northern Samar','Bobon'),('VIII','Northern Samar','Capul'),
  ('VIII','Northern Samar','Catarman'),('VIII','Northern Samar','Catubig'),
  ('VIII','Northern Samar','Gamay'),('VIII','Northern Samar','Laoang'),
  ('VIII','Northern Samar','Lapinig'),('VIII','Northern Samar','Las Navas'),
  ('VIII','Northern Samar','Lavezares'),('VIII','Northern Samar','Lope de Vega'),
  ('VIII','Northern Samar','Mapanas'),('VIII','Northern Samar','Mondragon'),
  ('VIII','Northern Samar','Palapag'),('VIII','Northern Samar','Pambujan'),
  ('VIII','Northern Samar','Rosario'),('VIII','Northern Samar','San Antonio'),
  ('VIII','Northern Samar','San Isidro'),('VIII','Northern Samar','San Jose'),
  ('VIII','Northern Samar','San Roque'),('VIII','Northern Samar','San Vicente'),
  ('VIII','Northern Samar','Silvino Lobos'),('VIII','Northern Samar','Victoria'),

  ('VIII','Samar','Almagro'),('VIII','Samar','Basey'),('VIII','Samar','Calbayog City'),
  ('VIII','Samar','Calbiga'),('VIII','Samar','Catbalogan City'),('VIII','Samar','Daram'),
  ('VIII','Samar','Gandara'),('VIII','Samar','Hinabangan'),('VIII','Samar','Jiabong'),
  ('VIII','Samar','Marabut'),('VIII','Samar','Matuguinao'),('VIII','Samar','Motiong'),
  ('VIII','Samar','Pagsanghan'),('VIII','Samar','Paranas'),('VIII','Samar','Pinabacdao'),
  ('VIII','Samar','San Jorge'),('VIII','Samar','San Jose de Buan'),
  ('VIII','Samar','San Sebastian'),('VIII','Samar','Santa Margarita'),
  ('VIII','Samar','Santa Rita'),('VIII','Samar','Santo Niño'),
  ('VIII','Samar','Tagapul-an'),('VIII','Samar','Talalora'),('VIII','Samar','Tarangnan'),
  ('VIII','Samar','Villareal'),('VIII','Samar','Zumarraga'),

  ('VIII','Southern Leyte','Anahawan'),('VIII','Southern Leyte','Bontoc'),
  ('VIII','Southern Leyte','Hinunangan'),('VIII','Southern Leyte','Hinundayan'),
  ('VIII','Southern Leyte','Libagon'),('VIII','Southern Leyte','Liloan'),
  ('VIII','Southern Leyte','Limasawa'),('VIII','Southern Leyte','Maasin City'),
  ('VIII','Southern Leyte','Macrohon'),('VIII','Southern Leyte','Malitbog'),
  ('VIII','Southern Leyte','Padre Burgos'),('VIII','Southern Leyte','Pintuyan'),
  ('VIII','Southern Leyte','Saint Bernard'),('VIII','Southern Leyte','San Francisco'),
  ('VIII','Southern Leyte','San Juan'),('VIII','Southern Leyte','San Ricardo'),
  ('VIII','Southern Leyte','Silago'),('VIII','Southern Leyte','Sogod'),
  ('VIII','Southern Leyte','Tomas Oppus'),

  -- ── Region IX ──────────────────────────────────────────────────────────────
  ('IX','Zamboanga del Norte','Baliguian'),('IX','Zamboanga del Norte','La Libertad'),
  ('IX','Zamboanga del Norte','Mutia'),('IX','Zamboanga del Norte','Sergio Osmeña Sr'),
  ('IX','Zamboanga del Norte','Jose Dalman'),('IX','Zamboanga del Norte','Gutalac'),
  ('IX','Zamboanga del Norte','Godod'),('IX','Zamboanga del Norte','Sirawai'),
  ('IX','Zamboanga del Norte','Tampilisan'),('IX','Zamboanga del Norte','Bacungan'),
  ('IX','Zamboanga del Norte','Kalawit'),('IX','Zamboanga del Norte','Dapitan City'),
  ('IX','Zamboanga del Norte','Dipolog City'),('IX','Zamboanga del Norte','Katipunan'),
  ('IX','Zamboanga del Norte','Labason'),('IX','Zamboanga del Norte','Liloy'),
  ('IX','Zamboanga del Norte','Manukan'),('IX','Zamboanga del Norte','Piñan'),
  ('IX','Zamboanga del Norte','Polanco'),('IX','Zamboanga del Norte','Rizal'),
  ('IX','Zamboanga del Norte','President Manuel A Roxas'),
  ('IX','Zamboanga del Norte','Saiyan'),('IX','Zamboanga del Norte','Salug'),
  ('IX','Zamboanga del Norte','Sibuco'),('IX','Zamboanga del Norte','Sibutad'),
  ('IX','Zamboanga del Norte','Sindangan'),('IX','Zamboanga del Norte','Siocon'),

  ('IX','Zamboanga del Sur','Aurora'),('IX','Zamboanga del Sur','Bayog'),
  ('IX','Zamboanga del Sur','Dimataling'),('IX','Zamboanga del Sur','Dinas'),
  ('IX','Zamboanga del Sur','Dumalinao'),('IX','Zamboanga del Sur','Dumingag'),
  ('IX','Zamboanga del Sur','Guipos'),('IX','Zamboanga del Sur','Josefina'),
  ('IX','Zamboanga del Sur','Kumalarang'),('IX','Zamboanga del Sur','Labangan'),
  ('IX','Zamboanga del Sur','Lakewood'),('IX','Zamboanga del Sur','Lapuyan'),
  ('IX','Zamboanga del Sur','Mahayag'),('IX','Zamboanga del Sur','Margosatubig'),
  ('IX','Zamboanga del Sur','Midsalip'),('IX','Zamboanga del Sur','Molave'),
  ('IX','Zamboanga del Sur','Pagadian City'),('IX','Zamboanga del Sur','Pitogo'),
  ('IX','Zamboanga del Sur','Ramon Magsaysay'),('IX','Zamboanga del Sur','San Miguel'),
  ('IX','Zamboanga del Sur','San Pablo'),('IX','Zamboanga del Sur','Sominot'),
  ('IX','Zamboanga del Sur','Tabina'),('IX','Zamboanga del Sur','Tambulig'),
  ('IX','Zamboanga del Sur','Tigbao'),('IX','Zamboanga del Sur','Tukuran'),
  ('IX','Zamboanga del Sur','Vincenzo A Sagun'),('IX','Zamboanga del Sur','Zamboanga City'),

  ('IX','Zamboanga Sibugay','Buug'),('IX','Zamboanga Sibugay','Imelda'),
  ('IX','Zamboanga Sibugay','Alicia'),('IX','Zamboanga Sibugay','Payao'),
  ('IX','Zamboanga Sibugay','Talusan'),('IX','Zamboanga Sibugay','Naga'),
  ('IX','Zamboanga Sibugay','Roseller T Lim'),('IX','Zamboanga Sibugay','Diplahan'),
  ('IX','Zamboanga Sibugay','Ipil'),('IX','Zamboanga Sibugay','Isabela City'),
  ('IX','Zamboanga Sibugay','Kabasalan'),('IX','Zamboanga Sibugay','Mabuhay'),
  ('IX','Zamboanga Sibugay','Malangas'),('IX','Zamboanga Sibugay','Olutanga'),
  ('IX','Zamboanga Sibugay','Siay'),('IX','Zamboanga Sibugay','Titay'),
  ('IX','Zamboanga Sibugay','Tungawan'),

  -- ── Region X ───────────────────────────────────────────────────────────────
  ('X','Bukidnon','Cabanglasan'),('X','Bukidnon','Dangcagan'),('X','Bukidnon','Don Carlos'),
  ('X','Bukidnon','Impasugong'),('X','Bukidnon','Kadingilan'),('X','Bukidnon','Kalilangan'),
  ('X','Bukidnon','Kibawe'),('X','Bukidnon','Lantapan'),('X','Bukidnon','Libona'),
  ('X','Bukidnon','Malaybalay City'),('X','Bukidnon','Malitbog'),
  ('X','Bukidnon','Manolo Fortich'),('X','Bukidnon','Maramag'),('X','Bukidnon','Baungon'),
  ('X','Bukidnon','Damulog'),('X','Bukidnon','Kitaotao'),('X','Bukidnon','Pangantucan'),
  ('X','Bukidnon','Quezon'),('X','Bukidnon','San Fernando'),('X','Bukidnon','Sumilao'),
  ('X','Bukidnon','Talakag'),('X','Bukidnon','Valencia City'),

  ('X','Camiguin','Catarman'),('X','Camiguin','Guinsiliban'),('X','Camiguin','Mambajao'),
  ('X','Camiguin','Mahinog'),('X','Camiguin','Sagay'),

  ('X','Lanao del Norte','Bacolod'),('X','Lanao del Norte','Baloi'),
  ('X','Lanao del Norte','Matungao'),('X','Lanao del Norte','Tagoloan'),
  ('X','Lanao del Norte','Pantar'),('X','Lanao del Norte','Pantao-Ragat'),
  ('X','Lanao del Norte','Poona Piagapo'),('X','Lanao del Norte','Baroy'),
  ('X','Lanao del Norte','Iligan City'),('X','Lanao del Norte','Kapatagan'),
  ('X','Lanao del Norte','Kauswagan'),('X','Lanao del Norte','Kolambogan'),
  ('X','Lanao del Norte','Lala'),('X','Lanao del Norte','Linamon'),
  ('X','Lanao del Norte','Magsaysay'),('X','Lanao del Norte','Maigo'),
  ('X','Lanao del Norte','Munai'),('X','Lanao del Norte','Nunungan'),
  ('X','Lanao del Norte','Salvador'),('X','Lanao del Norte','Sapad'),
  ('X','Lanao del Norte','Sultan Naga Dimaporo'),('X','Lanao del Norte','Tangkal'),
  ('X','Lanao del Norte','Tubod'),

  ('X','Misamis Occidental','Aloran'),('X','Misamis Occidental','Baliangao'),
  ('X','Misamis Occidental','Bonifacio'),('X','Misamis Occidental','Calamba'),
  ('X','Misamis Occidental','Clarin'),('X','Misamis Occidental','Concepcion'),
  ('X','Misamis Occidental','Don Victoriano Chiongbian'),
  ('X','Misamis Occidental','Jimenez'),('X','Misamis Occidental','Lopez Jaena'),
  ('X','Misamis Occidental','Oroquieta City'),('X','Misamis Occidental','Ozamiz City'),
  ('X','Misamis Occidental','Panaon'),('X','Misamis Occidental','Plaridel'),
  ('X','Misamis Occidental','Sapang Dalaga'),('X','Misamis Occidental','Sinacaban'),
  ('X','Misamis Occidental','Tangub City'),('X','Misamis Occidental','Tudela'),

  ('X','Misamis Oriental','Alubijid'),('X','Misamis Oriental','Balingasag'),
  ('X','Misamis Oriental','Balingoan'),('X','Misamis Oriental','Binuangan'),
  ('X','Misamis Oriental','Cagayan de Oro City'),('X','Misamis Oriental','Claveria'),
  ('X','Misamis Oriental','El Salvador City'),('X','Misamis Oriental','Gingoog City'),
  ('X','Misamis Oriental','Gitagum'),('X','Misamis Oriental','Initao'),
  ('X','Misamis Oriental','Jasaan'),('X','Misamis Oriental','Kinoguitan'),
  ('X','Misamis Oriental','Lagonglong'),('X','Misamis Oriental','Laguindingan'),
  ('X','Misamis Oriental','Libertad'),('X','Misamis Oriental','Lugait'),
  ('X','Misamis Oriental','Magsaysay'),('X','Misamis Oriental','Manticao'),
  ('X','Misamis Oriental','Medina'),('X','Misamis Oriental','Naawan'),
  ('X','Misamis Oriental','Opol'),('X','Misamis Oriental','Salay'),
  ('X','Misamis Oriental','Sugbongcogon'),('X','Misamis Oriental','Tagoloan'),
  ('X','Misamis Oriental','Talisayan'),('X','Misamis Oriental','Villanueva'),

  -- ── Region XI ──────────────────────────────────────────────────────────────
  ('XI','Davao de Oro','Compostela'),('XI','Davao de Oro','Laak'),
  ('XI','Davao de Oro','Mabini'),('XI','Davao de Oro','Maco'),
  ('XI','Davao de Oro','Maragusan'),('XI','Davao de Oro','Mawab'),
  ('XI','Davao de Oro','Monkayo'),('XI','Davao de Oro','Montevista'),
  ('XI','Davao de Oro','Nabunturan'),('XI','Davao de Oro','New Bataan'),
  ('XI','Davao de Oro','Pantukan'),

  ('XI','Davao del Norte','Asuncion'),('XI','Davao del Norte','Carmen'),
  ('XI','Davao del Norte','Braulio E Dujali'),('XI','Davao del Norte','Kapalong'),
  ('XI','Davao del Norte','New Corella'),('XI','Davao del Norte','Panabo City'),
  ('XI','Davao del Norte','Island Garden City of Samal'),
  ('XI','Davao del Norte','San Isidro'),('XI','Davao del Norte','Santo Tomas'),
  ('XI','Davao del Norte','Tagum City'),('XI','Davao del Norte','Talaingod'),

  ('XI','Davao del Sur','Bansalan'),('XI','Davao del Sur','Davao City'),
  ('XI','Davao del Sur','Digos City'),('XI','Davao del Sur','Hagonoy'),
  ('XI','Davao del Sur','Kiblawan'),('XI','Davao del Sur','Magsaysay'),
  ('XI','Davao del Sur','Malalag'),('XI','Davao del Sur','Matanao'),
  ('XI','Davao del Sur','Padada'),('XI','Davao del Sur','Santa Cruz'),
  ('XI','Davao del Sur','Sulop'),

  ('XI','Davao Occidental','Don Marcelino'),('XI','Davao Occidental','Jose Abad Santos'),
  ('XI','Davao Occidental','Malita'),('XI','Davao Occidental','Santa Maria'),
  ('XI','Davao Occidental','Sarangani'),

  ('XI','Davao Oriental','Baganga'),('XI','Davao Oriental','Banaybanay'),
  ('XI','Davao Oriental','Boston'),('XI','Davao Oriental','Caraga'),
  ('XI','Davao Oriental','Cateel'),('XI','Davao Oriental','Governor Generoso'),
  ('XI','Davao Oriental','Lupon'),('XI','Davao Oriental','Manay'),
  ('XI','Davao Oriental','Mati City'),('XI','Davao Oriental','San Isidro'),
  ('XI','Davao Oriental','Tarragona'),

  -- ── Region XII ─────────────────────────────────────────────────────────────
  ('XII','North Cotabato','Alamada'),('XII','North Cotabato','Aleosan'),
  ('XII','North Cotabato','Antipas'),('XII','North Cotabato','Arakan'),
  ('XII','North Cotabato','Banisilan'),('XII','North Cotabato','Carmen'),
  ('XII','North Cotabato','Cotabato City'),('XII','North Cotabato','Kabacan'),
  ('XII','North Cotabato','Kidapawan City'),('XII','North Cotabato','Libungan'),
  ('XII','North Cotabato','Magpet'),('XII','North Cotabato','Makilala'),
  ('XII','North Cotabato','Matalam'),('XII','North Cotabato','Midsayap'),
  ('XII','North Cotabato','M''lang'),('XII','North Cotabato','Pigcawayan'),
  ('XII','North Cotabato','Pikit'),('XII','North Cotabato','President Roxas'),
  ('XII','North Cotabato','Tulunan'),

  ('XII','Sarangani','Alabel'),('XII','Sarangani','Glan'),('XII','Sarangani','Kiamba'),
  ('XII','Sarangani','Maasim'),('XII','Sarangani','Maitum'),
  ('XII','Sarangani','Malapatan'),('XII','Sarangani','Malungon'),

  ('XII','South Cotabato','Banga'),('XII','South Cotabato','General Santos City'),
  ('XII','South Cotabato','Koronadal City'),('XII','South Cotabato','Lake Sebu'),
  ('XII','South Cotabato','Norala'),('XII','South Cotabato','Polomolok'),
  ('XII','South Cotabato','Santo Niño'),('XII','South Cotabato','Surallah'),
  ('XII','South Cotabato','Tampakan'),('XII','South Cotabato','Tantangan'),
  ('XII','South Cotabato','T''boli'),('XII','South Cotabato','Tupi'),

  ('XII','Sultan Kudarat','Bagumbayan'),('XII','Sultan Kudarat','Colombio'),
  ('XII','Sultan Kudarat','Esperanza'),('XII','Sultan Kudarat','Isulan'),
  ('XII','Sultan Kudarat','Kalamansig'),('XII','Sultan Kudarat','Lambayong'),
  ('XII','Sultan Kudarat','Lebak'),('XII','Sultan Kudarat','Lutayan'),
  ('XII','Sultan Kudarat','Palimbang'),('XII','Sultan Kudarat','President Quirino'),
  ('XII','Sultan Kudarat','Senator Ninoy Aquino'),('XII','Sultan Kudarat','Tacurong City'),

  -- ── Region XIII / CARAGA ───────────────────────────────────────────────────
  ('XIII','Agusan del Norte','Buenavista'),('XIII','Agusan del Norte','Butuan City'),
  ('XIII','Agusan del Norte','Cabadbaran City'),('XIII','Agusan del Norte','Carmen'),
  ('XIII','Agusan del Norte','Jabonga'),('XIII','Agusan del Norte','Kitcharao'),
  ('XIII','Agusan del Norte','Las Nieves'),('XIII','Agusan del Norte','Magallanes'),
  ('XIII','Agusan del Norte','Nasipit'),('XIII','Agusan del Norte','Remedios T Romualdez'),
  ('XIII','Agusan del Norte','Santiago'),('XIII','Agusan del Norte','Tubay'),

  ('XIII','Agusan del Sur','Bayugan City'),('XIII','Agusan del Sur','Bunawan'),
  ('XIII','Agusan del Sur','Esperanza'),('XIII','Agusan del Sur','La Paz'),
  ('XIII','Agusan del Sur','Loreto'),('XIII','Agusan del Sur','Prosperidad'),
  ('XIII','Agusan del Sur','Rosario'),('XIII','Agusan del Sur','San Francisco'),
  ('XIII','Agusan del Sur','San Luis'),('XIII','Agusan del Sur','Sibagat'),
  ('XIII','Agusan del Sur','Santa Josefa'),('XIII','Agusan del Sur','Talacogon'),
  ('XIII','Agusan del Sur','Trento'),('XIII','Agusan del Sur','Veruela'),

  ('XIII','Dinagat Islands','Basilisa'),('XIII','Dinagat Islands','Cagdianao'),
  ('XIII','Dinagat Islands','Dinagat'),('XIII','Dinagat Islands','Libjo'),
  ('XIII','Dinagat Islands','Loreto'),('XIII','Dinagat Islands','San Jose'),
  ('XIII','Dinagat Islands','Tubajon'),

  ('XIII','Surigao del Norte','Alegria'),('XIII','Surigao del Norte','Bacuag'),
  ('XIII','Surigao del Norte','Burgos'),('XIII','Surigao del Norte','Claver'),
  ('XIII','Surigao del Norte','Dapa'),('XIII','Surigao del Norte','Del Carmen'),
  ('XIII','Surigao del Norte','General Luna'),('XIII','Surigao del Norte','Gigaquit'),
  ('XIII','Surigao del Norte','Mainit'),('XIII','Surigao del Norte','Malimono'),
  ('XIII','Surigao del Norte','Pilar'),('XIII','Surigao del Norte','Placer'),
  ('XIII','Surigao del Norte','San Benito'),('XIII','Surigao del Norte','San Francisco'),
  ('XIII','Surigao del Norte','San Isidro'),('XIII','Surigao del Norte','Sison'),
  ('XIII','Surigao del Norte','Socorro'),('XIII','Surigao del Norte','Santa Monica'),
  ('XIII','Surigao del Norte','Surigao City'),('XIII','Surigao del Norte','Tagana-an'),
  ('XIII','Surigao del Norte','Tubod'),

  ('XIII','Surigao del Sur','Barobo'),('XIII','Surigao del Sur','Bayabas'),
  ('XIII','Surigao del Sur','Bislig City'),('XIII','Surigao del Sur','Cagwait'),
  ('XIII','Surigao del Sur','Cantilan'),('XIII','Surigao del Sur','Carrascal'),
  ('XIII','Surigao del Sur','Carmen'),('XIII','Surigao del Sur','Cortes'),
  ('XIII','Surigao del Sur','Hinatuan'),('XIII','Surigao del Sur','Lanuza'),
  ('XIII','Surigao del Sur','Lianga'),('XIII','Surigao del Sur','Lingig'),
  ('XIII','Surigao del Sur','Madrid'),('XIII','Surigao del Sur','Marihatag'),
  ('XIII','Surigao del Sur','San Agustin'),('XIII','Surigao del Sur','San Miguel'),
  ('XIII','Surigao del Sur','Tagbina'),('XIII','Surigao del Sur','Tago'),
  ('XIII','Surigao del Sur','Tandag City'),

  -- ── BARMM ──────────────────────────────────────────────────────────────────
  ('BARMM','Basilan','Akbar'),('BARMM','Basilan','Al-Barka'),
  ('BARMM','Basilan','Hadji Mohammad Ajul'),('BARMM','Basilan','Hadji Muhtamad'),
  ('BARMM','Basilan','Lamitan City'),('BARMM','Basilan','Lantawan'),
  ('BARMM','Basilan','Maluso'),('BARMM','Basilan','Sumisip'),
  ('BARMM','Basilan','Tabuan-Lasa'),('BARMM','Basilan','Tipo-Tipo'),
  ('BARMM','Basilan','Tuburan'),('BARMM','Basilan','Ungkaya Pukan'),

  ('BARMM','Lanao del Sur','Bacolod-Kalawi'),('BARMM','Lanao del Sur','Balabagan'),
  ('BARMM','Lanao del Sur','Balindong'),('BARMM','Lanao del Sur','Bayang'),
  ('BARMM','Lanao del Sur','Binidayan'),('BARMM','Lanao del Sur','Buadiposo-Buntong'),
  ('BARMM','Lanao del Sur','Bubong'),('BARMM','Lanao del Sur','Bumbaran'),
  ('BARMM','Lanao del Sur','Butig'),('BARMM','Lanao del Sur','Calanogas'),
  ('BARMM','Lanao del Sur','Ditsaan-Ramain'),('BARMM','Lanao del Sur','Ganassi'),
  ('BARMM','Lanao del Sur','Kapai'),('BARMM','Lanao del Sur','Kapatagan'),
  ('BARMM','Lanao del Sur','Lumba-Bayabao'),('BARMM','Lanao del Sur','Lumbaca-Unayan'),
  ('BARMM','Lanao del Sur','Lumbatan'),('BARMM','Lanao del Sur','Lumbayanague'),
  ('BARMM','Lanao del Sur','Madalum'),('BARMM','Lanao del Sur','Madamba'),
  ('BARMM','Lanao del Sur','Maguing'),('BARMM','Lanao del Sur','Malabang'),
  ('BARMM','Lanao del Sur','Marantao'),('BARMM','Lanao del Sur','Marawi City'),
  ('BARMM','Lanao del Sur','Marogong'),('BARMM','Lanao del Sur','Masiu'),
  ('BARMM','Lanao del Sur','Mulondo'),('BARMM','Lanao del Sur','Pagayawan'),
  ('BARMM','Lanao del Sur','Piagapo'),('BARMM','Lanao del Sur','Picong'),
  ('BARMM','Lanao del Sur','Poona Bayabao'),('BARMM','Lanao del Sur','Pualas'),
  ('BARMM','Lanao del Sur','Saguiaran'),('BARMM','Lanao del Sur','Sultan Dumalondong'),
  ('BARMM','Lanao del Sur','Tagoloan II'),('BARMM','Lanao del Sur','Tamparan'),
  ('BARMM','Lanao del Sur','Taraka'),('BARMM','Lanao del Sur','Tubaran'),
  ('BARMM','Lanao del Sur','Tugaya'),('BARMM','Lanao del Sur','Wao'),

  ('BARMM','Maguindanao del Norte','Ampatuan'),('BARMM','Maguindanao del Norte','Barira'),
  ('BARMM','Maguindanao del Norte','Buldon'),('BARMM','Maguindanao del Norte','Buluan'),
  ('BARMM','Maguindanao del Norte','Datu Abdullah Sangki'),
  ('BARMM','Maguindanao del Norte','Datu Anggal Midtimbang'),
  ('BARMM','Maguindanao del Norte','Datu Blah T Sinsuat'),
  ('BARMM','Maguindanao del Norte','Datu Hoffer Ampatuan'),
  ('BARMM','Maguindanao del Norte','Datu Montawal'),
  ('BARMM','Maguindanao del Norte','Datu Odin Sinsuat'),
  ('BARMM','Maguindanao del Norte','Datu Paglas'),('BARMM','Maguindanao del Norte','Datu Piang'),
  ('BARMM','Maguindanao del Norte','Datu Salibo'),
  ('BARMM','Maguindanao del Norte','Datu Saudi Ampatuan'),
  ('BARMM','Maguindanao del Norte','Datu Unsay'),
  ('BARMM','Maguindanao del Norte','General Salipada K Pendatun'),
  ('BARMM','Maguindanao del Norte','Guindulungan'),
  ('BARMM','Maguindanao del Norte','Kabuntalan'),('BARMM','Maguindanao del Norte','Mamasapano'),
  ('BARMM','Maguindanao del Norte','Mangudadatu'),('BARMM','Maguindanao del Norte','Matanog'),
  ('BARMM','Maguindanao del Norte','Northern Kabuntalan'),
  ('BARMM','Maguindanao del Norte','Pagalungan'),('BARMM','Maguindanao del Norte','Paglat'),
  ('BARMM','Maguindanao del Norte','Pandag'),('BARMM','Maguindanao del Norte','Parang'),
  ('BARMM','Maguindanao del Norte','Rajah Buayan'),
  ('BARMM','Maguindanao del Norte','Shariff Aguak'),
  ('BARMM','Maguindanao del Norte','Shariff Saydona Mustapha'),
  ('BARMM','Maguindanao del Norte','South Upi'),
  ('BARMM','Maguindanao del Norte','Sultan Mastura'),
  ('BARMM','Maguindanao del Norte','Sultan sa Barongis'),
  ('BARMM','Maguindanao del Norte','Talayan'),('BARMM','Maguindanao del Norte','Talitay'),
  ('BARMM','Maguindanao del Norte','Upi'),

  ('BARMM','Maguindanao del Sur','Ampatuan'),('BARMM','Maguindanao del Sur','Barira'),
  ('BARMM','Maguindanao del Sur','Buldon'),('BARMM','Maguindanao del Sur','Buluan'),
  ('BARMM','Maguindanao del Sur','Datu Abdullah Sangki'),
  ('BARMM','Maguindanao del Sur','Datu Anggal Midtimbang'),
  ('BARMM','Maguindanao del Sur','Datu Blah T Sinsuat'),
  ('BARMM','Maguindanao del Sur','Datu Hoffer Ampatuan'),
  ('BARMM','Maguindanao del Sur','Datu Montawal'),
  ('BARMM','Maguindanao del Sur','Datu Odin Sinsuat'),
  ('BARMM','Maguindanao del Sur','Datu Paglas'),('BARMM','Maguindanao del Sur','Datu Piang'),
  ('BARMM','Maguindanao del Sur','Datu Salibo'),
  ('BARMM','Maguindanao del Sur','Datu Saudi Ampatuan'),
  ('BARMM','Maguindanao del Sur','Datu Unsay'),
  ('BARMM','Maguindanao del Sur','General Salipada K Pendatun'),
  ('BARMM','Maguindanao del Sur','Guindulungan'),
  ('BARMM','Maguindanao del Sur','Kabuntalan'),('BARMM','Maguindanao del Sur','Mamasapano'),
  ('BARMM','Maguindanao del Sur','Mangudadatu'),('BARMM','Maguindanao del Sur','Matanog'),
  ('BARMM','Maguindanao del Sur','Northern Kabuntalan'),
  ('BARMM','Maguindanao del Sur','Pagalungan'),('BARMM','Maguindanao del Sur','Paglat'),
  ('BARMM','Maguindanao del Sur','Pandag'),('BARMM','Maguindanao del Sur','Parang'),
  ('BARMM','Maguindanao del Sur','Rajah Buayan'),
  ('BARMM','Maguindanao del Sur','Shariff Aguak'),
  ('BARMM','Maguindanao del Sur','Shariff Saydona Mustapha'),
  ('BARMM','Maguindanao del Sur','South Upi'),
  ('BARMM','Maguindanao del Sur','Sultan Mastura'),
  ('BARMM','Maguindanao del Sur','Sultan sa Barongis'),
  ('BARMM','Maguindanao del Sur','Talayan'),('BARMM','Maguindanao del Sur','Talitay'),
  ('BARMM','Maguindanao del Sur','Upi'),

  ('BARMM','Sulu','Banguingui'),('BARMM','Sulu','Hadji Panglima Tahil'),
  ('BARMM','Sulu','Indanan'),('BARMM','Sulu','Jolo'),
  ('BARMM','Sulu','Kalingalan Caluang'),('BARMM','Sulu','Lugus'),
  ('BARMM','Sulu','Luuk'),('BARMM','Sulu','Maimbung'),
  ('BARMM','Sulu','Old Panamao'),('BARMM','Sulu','Omar'),
  ('BARMM','Sulu','Pandami'),('BARMM','Sulu','Panglima Estino'),
  ('BARMM','Sulu','Pangutaran'),('BARMM','Sulu','Parang'),
  ('BARMM','Sulu','Pata'),('BARMM','Sulu','Patikul'),
  ('BARMM','Sulu','Siasi'),('BARMM','Sulu','Talipao'),('BARMM','Sulu','Tapul'),

  ('BARMM','Tawi-Tawi','Bongao'),('BARMM','Tawi-Tawi','Languyan'),
  ('BARMM','Tawi-Tawi','Mapun'),('BARMM','Tawi-Tawi','Panglima Sugala'),
  ('BARMM','Tawi-Tawi','Sapa-Sapa'),('BARMM','Tawi-Tawi','Sibutu'),
  ('BARMM','Tawi-Tawi','Simunul'),('BARMM','Tawi-Tawi','Sitangkai'),
  ('BARMM','Tawi-Tawi','South Ubian'),('BARMM','Tawi-Tawi','Tandubas'),
  ('BARMM','Tawi-Tawi','Turtle Islands'),

  -- ── NIR ────────────────────────────────────────────────────────────────────
  ('NIR','Negros Occidental','Bacolod City'),('NIR','Negros Occidental','Bago City'),
  ('NIR','Negros Occidental','Binalbagan'),('NIR','Negros Occidental','Cadiz City'),
  ('NIR','Negros Occidental','Calatrava'),('NIR','Negros Occidental','Candoni'),
  ('NIR','Negros Occidental','Cauayan'),('NIR','Negros Occidental','Enrique B Magalona'),
  ('NIR','Negros Occidental','Escalante City'),('NIR','Negros Occidental','Himamaylan City'),
  ('NIR','Negros Occidental','Hinigaran'),('NIR','Negros Occidental','Hinoba-an'),
  ('NIR','Negros Occidental','Ilog'),('NIR','Negros Occidental','Kabankalan City'),
  ('NIR','Negros Occidental','La Carlota City'),('NIR','Negros Occidental','La Castellana'),
  ('NIR','Negros Occidental','Manapla'),('NIR','Negros Occidental','Moises Padilla'),
  ('NIR','Negros Occidental','Murcia'),('NIR','Negros Occidental','Pulupandan'),
  ('NIR','Negros Occidental','Pontevedra'),('NIR','Negros Occidental','Salvador Benedicto'),
  ('NIR','Negros Occidental','Sagay City'),('NIR','Negros Occidental','San Carlos City'),
  ('NIR','Negros Occidental','San Enrique'),('NIR','Negros Occidental','Silay City'),
  ('NIR','Negros Occidental','Sipalay City'),('NIR','Negros Occidental','Talisay City'),
  ('NIR','Negros Occidental','Toboso'),('NIR','Negros Occidental','Valladolid'),
  ('NIR','Negros Occidental','Victorias City'),

  ('NIR','Negros Oriental','Amlan'),('NIR','Negros Oriental','Ayungon'),
  ('NIR','Negros Oriental','Bacong'),('NIR','Negros Oriental','Bais City'),
  ('NIR','Negros Oriental','Basay'),('NIR','Negros Oriental','Bayawan City'),
  ('NIR','Negros Oriental','Bindoy'),('NIR','Negros Oriental','Canlaon City'),
  ('NIR','Negros Oriental','Dauin'),('NIR','Negros Oriental','Dumaguete City'),
  ('NIR','Negros Oriental','Guihulngan City'),('NIR','Negros Oriental','Jimalalud'),
  ('NIR','Negros Oriental','La Libertad'),('NIR','Negros Oriental','Mabinay'),
  ('NIR','Negros Oriental','Manjuyod'),('NIR','Negros Oriental','Pamplona'),
  ('NIR','Negros Oriental','San Jose'),('NIR','Negros Oriental','Siaton'),
  ('NIR','Negros Oriental','Sibulan'),('NIR','Negros Oriental','Santa Catalina'),
  ('NIR','Negros Oriental','Tanjay City'),('NIR','Negros Oriental','Tayasan'),
  ('NIR','Negros Oriental','Valencia'),('NIR','Negros Oriental','Vallehermoso'),
  ('NIR','Negros Oriental','Zamboanguita')

) AS v(rcode, pname, cname)
JOIN wims.ref_regions r ON r.region_code = v.rcode
JOIN wims.ref_provinces p ON p.province_name = v.pname AND p.region_id = r.region_id
WHERE NOT EXISTS (
  SELECT 1 FROM wims.ref_cities c
  WHERE c.province_id = p.province_id AND c.city_name = v.cname
);

COMMIT;
