-- 33_incident_ai_narrative.sql
-- Dependencies: 04_import_incidents.sql, 19_reference_number.sql
-- Idempotent: YES

BEGIN;

ALTER TABLE wims.fire_incidents
    ADD COLUMN IF NOT EXISTS ai_narrative TEXT,
    ADD COLUMN IF NOT EXISTS ai_narrative_confidence DOUBLE PRECISION
        CHECK (ai_narrative_confidence IS NULL
               OR (ai_narrative_confidence >= 0.0
                   AND ai_narrative_confidence <= 1.0));

COMMENT ON COLUMN wims.fire_incidents.ai_narrative IS
    'AI-generated plain-language summary of this incident. '
    'Generated by Qwen2.5-3B via Ollama on NATIONAL_ANALYST request.';

COMMENT ON COLUMN wims.fire_incidents.ai_narrative_confidence IS
    'Model confidence score for ai_narrative (0.0-1.0). NULL if not yet generated.';

CREATE INDEX IF NOT EXISTS idx_fire_incidents_ai_narrative_null
    ON wims.fire_incidents (incident_id)
    WHERE ai_narrative IS NULL
      AND verification_status = 'VERIFIED';

COMMIT;